// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzczqjunmvjprozvaavw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Y3pxanVubXZqcHJvenZhYXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NDI1MjksImV4cCI6MjA3NzIxODUyOX0.A2vJZCaBG9dVAX4m1TAle-9QnBwvpTmCSLVEzuGq6sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});